# ---- Core Settings ----
set -g prefix C-s
unbind C-b
bind C-s send-prefix

set -g mouse on
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-position top
set -g renumber-windows on

# Vim-style copy mode
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard"

# ---- Plugins ----
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'

# ---- Dracula Configuration ----
set -g @dracula-plugins "ssh-session weather"

# 2. Appearance
set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons true
set -g @dracula-transparent-powerline-bg true
set -g @dracula-show-left-icon session 

# 3. Weather Settings
set -g @dracula-show-fahrenheit false
set -g @dracula-weather-format "%l"
# set -g @dracula-fixed-location "Kathmandu"

# 4. SSH & Other Tweaks
set -g @dracula-show-ssh-only-when-connected true
set -g @dracula-show-flags true
set -g @dracula-show-empty-plugins false
set -g @dracula-narrow-plugins "weather"

# Resurrect / Continuum settings
set -g @continuum-restore 'on'

# Initialize TPM (Keep this at the bottom)
run '~/.tmux/plugins/tpm/tpm'
